### ISSUE TITLE
SSL Support using Let's Encrypt

### ISSUE THREAD

**Issue by tclose** [NrgXnat/xnat-docker-compose#1]
We are planning to add support for SSL to the docker compose script using Let's Encrypt

**Comment by koekie** [comment]
Here is an example of a docker compose file I have for installing minio with SSL support using Let's Encrypt, I guess this will be as easy as just replacing the minio service with an xnat service ;)

```yaml
version: '2'

services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "./volumes/proxy/vhost.d:/etc/nginx/vhost.d:ro"
      - "/usr/share/nginx/html"
      - "./volumes/proxy/certs:/etc/nginx/certs:ro"
    networks:
      - proxy-tier
    
  nginx-gen:
    restart: always
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./volumes/proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    networks:
      - proxy-tier
    depends_on:
      - nginx

  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion 
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./volumes/proxy/certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
    depends_on:
      - nginx-gen


  minio:
    restart: always
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
    volumes:
      - /data/minio:/export
    environment:
      - "VIRTUAL_NETWORK=nginx-proxy"
    command: server /export
    networks:
      - proxy-tier
    depends_on:
      - letsencrypt-nginx-proxy-companion

networks:
  proxy-tier:
    external:
      name: nginx-proxy
```
