### ISSUE TITLE
Admin user cannot use config page

### ISSUE THREAD

**Issue by pvannierop** [NrgXnat/xnat-docker-compose#37]
Overall I experience many issues deploying your docker-compose solution. I encounter:

- Error that causes the database not to initiate as described [here](https://github.com/NrgXnat/xnat-docker-compose/issues/28).
- The ngix proxy not starting (that is at least my diagnosis) as described [here](https://github.com/NrgXnat/xnat-docker-compose/issues/20).

# Problem
To test drive XNAT I have created by own docker compose solution that uses an Apache HTTPD reverse proxy that hosts XNAT at address `https://hostname/xnat`.

When doing this all initialization is fine, but while logging in as admin after first start I encounter session problems. As soon as I log in, immediately a message `User session ended` is shown and I cannot use the config page (see movie below). The page continues to auto-reload every 30 seconds or so.

Do you know what may be the problem here? Do you have suggestions to find the cause?

![Peek 2020-06-23 16-27](https://user-images.githubusercontent.com/745885/85416915-4dd4a400-b56f-11ea-9491-cf31c9020ee0.gif)

# System setup

## Operating system
- Ubuntu 18.04
- Docker version 19.03.11, build 42e35e61f3
- docker-compose version 1.25.4, build 8d51620a

## Apache HTTPD config

Reverse proxy that hosts XNAT at address `https://localhost/xnat`.

```
Listen 80
Listen 443

<VirtualHost *:80>
  ServerName localhost
  Redirect / https://localhost/
</VirtualHost>

<VirtualHost *:443>
  SSLEngine on
  SSLCertificateFile /etc/ssl/cbio_https/cert.crt
  SSLCertificateKeyFile /etc/ssl/cbio_https/key.key
  ServerName localhost

  Header always set Strict-Transport-Security "max-age=15768000"

  ErrorLog /tmp/cbio_https_error.log
  LogLevel warn
  CustomLog /tmp/cbio_https_access.log combined

  ProxyPass /xnat http://xnat:8080/xnat
  ProxyPassReverse /xnat http://xnat:8080/xnat

  ProxyPreserveHost On

  <Location "/">
    AuthType None
    Require all granted
  </Location>

</VirtualHost>
```

## docker compose

The XNAT service is built with `TOMCAT_XNAT_FOLDER` set to `xnat` to support the `https://localhost/xnat` URL pattern.

```
version: '2.4'
networks:
  xnat-net:
    name: xnat-net

services:
  xnat:
    build:
      context: https://github.com/NrgXnat/xnat-docker-compose.git#:xnat
      args:
        XNAT_VER: '1.7.6'
        XNAT_DATASOURCE_DRIVER: 'org.postgresql.Driver'
        XNAT_DATASOURCE_URL: 'jdbc:postgresql://xnat-db/xnat'
        XNAT_DATASOURCE_USERNAME: 'xnat'
        XNAT_DATASOURCE_PASSWORD: 'xnat'
        XNAT_HIBERNATE_DIALECT: 'org.hibernate.dialect.PostgreSQL9Dialect'
        TOMCAT_XNAT_FOLDER: xnat
        XNAT_ROOT: /data/xnat
        XNAT_HOME: /data/xnat/home
    container_name: xnat
    networks:
      - xnat-net
    volumes:
      - ./client/xnat/plugins:/data/xnat/home/plugins
      - ./log/xnat:/data/xnat/home/logs
      - ${XNAT_FILE_DIR:-../xnat_application/}/archive:/data/xnat/archive
      - ${XNAT_FILE_DIR:-../xnat_application/}/build:/data/xnat/build
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - xnat-db
    environment:
      - CATALINA_OPTS=-Xms128m -Xmx2048m -Dxnat.home=/data/xnat/home
      - XNAT_HOME=/data/xnat/home

  xnat-db:
    build:
      context: https://github.com/NrgXnat/xnat-docker-compose.git#:postgres
    container_name: xnatdb
    networks:
      - xnat-net
    volumes:
      - ${XNAT_DATA_DIR:-../xnat_files/}:/var/lib/postgresql/data
    expose:
      - "5432"

  apache-proxy:
    networks:
      - xnat-net
    image: httpd:2.4.29
    container_name: apache-proxy
    restart: always
    volumes:
      - ./service/apache-proxy/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./service/apache-proxy/virtual-hosts/keycloak.conf:/usr/local/apache2/conf/sites/keycloak.conf:ro
      - ${PROXY_SSL_CERTIFICATE:-./client/ssl_cert/cert.crt}:/etc/ssl/cbio_https/cert.crt:ro
      - ${PROXY_SSL_KEY:-./client/ssl_cert/key.key}:/etc/ssl/cbio_https/key.key:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - xnat
```
