### ISSUE TITLE
Use nginx-proxy to trivially support SSL

### ISSUE THREAD

**Issue by dmd** [NrgXnat/xnat-docker-compose#62]
Just a suggestion/recommendation:

Setting up SSL can be trivial, using https://github.com/nginx-proxy/nginx-proxy !

In `docker-compose.yml`, instead of the current `xnat-nginx` stanza, use this instead:

```
  xnat-nginx:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /PATH/TO/YOUR/SSL-CERTS:/etc/nginx/certs:ro
```

In `/PATH/TO/YOUR/SSL-CERTS`, you need `your.hostname.edu.key` and `your.hostname.edu.crt`.

Finally, two more lines to add to `docker-compose`. In the `environment` stanza, add:

```
    - VIRTUAL_HOST=your.hostname.edu
    - VIRTUAL_PORT=8080
```

That's it! Now you've got an SSL proxy!
